Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false
